// src/ui/components/CombatAnnounce.tsx
import { useEffect, useState } from 'preact/hooks'
import { announceText } from '../state'

interface AnnounceItem {
  id: number
  text: string
}

let announceCounter = 0

export function CombatAnnounce() {
  const text = announceText.value
  const [items, setItems] = useState<AnnounceItem[]>([])

  useEffect(() => {
    if (!text) return
    const id = ++announceCounter
    setItems((prev) => [...prev, { id, text }])
    const timer = setTimeout(() => {
      setItems((prev) => prev.filter((item) => item.id !== id))
    }, 2000)
    return () => clearTimeout(timer)
  }, [text])

  return (
    <div
      style={{
        position: 'absolute', top: '20%', left: '50%', transform: 'translateX(-50%)',
        pointerEvents: 'none', zIndex: 60,
      }}
    >
      {items.map((item) => (
        <div
          key={item.id}
          style={{
            fontSize: 28, fontWeight: 300, letterSpacing: 6,
            color: '#e0e0e0', textShadow: '0 0 12px rgba(0,0,0,0.8)',
            animation: 'announceIn 2s ease-out forwards',
          }}
        >
          {item.text}
        </div>
      ))}
    </div>
  )
}

// src/components/hud/CombatAnnounce.vue
<script setup lang="ts">
import { ref, watch } from 'vue'
import { useBattleStore } from '@/stores/battle'

interface AnnounceItem {
  id: number
  text: string
}

const battle = useBattleStore()
const items = ref<AnnounceItem[]>([])
let announceCounter = 0

watch(
  () => battle.announceText,
  (text) => {
    if (!text) return
    const id = ++announceCounter
    items.value = [...items.value, { id, text }]
    setTimeout(() => {
      items.value = items.value.filter((item) => item.id !== id)
    }, 2000)
  }
)
</script>

<template lang="pug">
.combat-announce
  .combat-announce__text(v-for="item in items" :key="item.id") {{ item.text }}
</template>

<style lang="scss" scoped>
.combat-announce {
  position: absolute;
  top: 20%;
  left: 50%;
  transform: translateX(-50%);
  pointer-events: none;
  z-index: 60;
}

.combat-announce__text {
  font-size: 28px;
  font-weight: 300;
  letter-spacing: 6px;
  color: #e0e0e0;
  text-shadow: 0 0 12px rgba(0, 0, 0, 0.8);
  animation: announceIn 2s ease-out forwards;
}

@keyframes announceIn {
  0% {
    opacity: 1;
  }
  40% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
</style>
