// src/ui/components/Tooltip.tsx
import { signal } from '@preact/signals'

interface TooltipState {
  html: string
  x: number
  y: number
}

export const tooltipState = signal<TooltipState | null>(null)

export function showTooltip(html: string, x: number, y: number) {
  tooltipState.value = { html, x, y }
}

export function hideTooltip() {
  tooltipState.value = null
}

export function Tooltip() {
  const state = tooltipState.value
  if (!state) return null

  return (
    <div
      style={{
        position: 'fixed', zIndex: 200, pointerEvents: 'none',
        background: 'linear-gradient(180deg, rgba(30,28,24,0.97) 0%, rgba(18,16,14,0.97) 100%)',
        border: '2px solid #8b7440',
        borderRadius: 6, padding: '10px 14px',
        fontSize: 12, color: '#ccc', lineHeight: 1.6,
        maxWidth: 280,
        boxShadow: '0 0 1px rgba(184,160,106,0.4), 0 4px 12px rgba(0,0,0,0.6)',
        left: state.x, top: state.y,
        transform: 'translate(-50%, calc(-100% - 8px))',
      }}
      dangerouslySetInnerHTML={{ __html: state.html }}
    />
  )
}

// src/components/hud/Tooltip.vue
<script setup lang="ts">
import { computed, nextTick, ref, useTemplateRef, watch } from 'vue'
import { useTooltip } from '@/composables/use-tooltip'

const { state } = useTooltip()
const tooltipEl = useTemplateRef<HTMLDivElement>('tooltip')
const measuredHeight = ref(0)

watch(
  state,
  async (s) => {
    if (!s) {
      measuredHeight.value = 0
      return
    }
    await nextTick()
    if (tooltipEl.value) {
      measuredHeight.value = tooltipEl.value.offsetHeight
    }
  },
  { immediate: true, flush: 'post' },
)

const style = computed(() => {
  if (!state.value) return {}
  const { x, y } = state.value
  const margin = 12
  const h = measuredHeight.value || 100
  const fitsAbove = y - margin - h >= 4
  const top = fitsAbove ? y - margin - h : y + margin
  return {
    left: x + 'px',
    top: top + 'px',
  }
})
</script>

<template lang="pug">
.tooltip(v-if="state" ref="tooltip" :style="style")
  div(v-html="state.html")
</template>

<style lang="scss" scoped>
.tooltip {
  position: fixed;
  z-index: 200;
  pointer-events: none;
  background: linear-gradient(
    180deg,
    rgba(30, 28, 24, 0.97) 0%,
    rgba(18, 16, 14, 0.97) 100%
  );
  border: 2px solid #8b7440;
  border-radius: 6px;
  padding: 10px 14px;
  font-size: 12px;
  color: #ccc;
  line-height: 1.6;
  max-width: 280px;
  box-shadow:
    0 0 1px rgba(184, 160, 106, 0.4),
    0 4px 12px rgba(0, 0, 0, 0.6);
}
</style>
