// src/components/hud/PauseMenu.vue
<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useBattleStore } from '@/stores/battle'
import { getActiveScene } from '@/game/battle-runner'

const battle = useBattleStore()
const router = useRouter()
const emit = defineEmits<{ retry: []; resume: [] }>()

function onResume() {
  getActiveScene()?.resume()
  emit('resume')
}

function onRetry() {
  emit('retry')
}

function onQuit() {
  router.push('/')
}
</script>

<template lang="pug">
.pause-menu(v-if="battle.paused && !battle.battleOver")
  h2.pause-menu__title PAUSED
  button.pause-menu__btn(@click="onResume") Resume
  button.pause-menu__btn(@click="onRetry") Retry
  button.pause-menu__btn(@click="onQuit") Quit to Menu
</template>

<style lang="scss" scoped>
.pause-menu {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  background: rgba(0, 0, 0, 0.6);
  z-index: 90;
  pointer-events: auto;
}

.pause-menu__title {
  font-size: 28px;
  color: #ddd;
  margin-bottom: 30px;
  font-weight: 300;
  letter-spacing: 6px;
}

.pause-menu__btn {
  padding: 10px 28px;
  font-size: 14px;
  margin: 6px;
  background: rgba(255, 255, 255, 0.08);
  color: #bbb;
  border: 1px solid rgba(255, 255, 255, 0.15);
  border-radius: 3px;
  cursor: pointer;
  letter-spacing: 1px;
  min-width: 160px;
  pointer-events: auto;
}
</style>

// src/ui/components/PauseMenu.tsx
import { useLocation } from 'preact-iso'
import { paused } from '../state'

interface PauseMenuProps {
  onRetry: () => void
}

export function PauseMenu({ onRetry }: PauseMenuProps) {
  if (!paused.value) return null

  const { route } = useLocation()

  const btnStyle = {
    padding: '10px 28px', fontSize: 14, margin: 6,
    background: 'rgba(255,255,255,0.08)', color: '#bbb',
    border: '1px solid rgba(255,255,255,0.15)', borderRadius: 3,
    cursor: 'pointer', letterSpacing: 1, minWidth: 160,
    pointerEvents: 'auto' as const,
  }

  return (
    <div
      style={{
        position: 'absolute', top: 0, left: 0, width: '100%', height: '100%',
        display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
        background: 'rgba(0,0,0,0.6)', zIndex: 90, pointerEvents: 'auto',
      }}
    >
      <h2
        style={{
          fontSize: 28, color: '#ddd', marginBottom: 30,
          fontWeight: 300, letterSpacing: 6,
        }}
      >
        PAUSED
      </h2>
      <button style={btnStyle} onClick={() => { paused.value = false }}>
        Resume
      </button>
      <button style={btnStyle} onClick={onRetry}>
        Retry
      </button>
      <button
        style={btnStyle}
        onClick={() => {
          window.history.pushState(null, '', '/')
          window.dispatchEvent(new PopStateEvent('popstate'))
        }}
      >
        Quit to Menu
      </button>
    </div>
  )
}
