// src/components/hud/SkillBar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useBattleStore } from '@/stores/battle'
import { useTooltip } from '@/composables/use-tooltip'
import { buildSkillTooltip } from '@/components/hud/tooltip-builders'

const battle = useBattleStore()
const tooltip = useTooltip()

const activeBuffIds = computed(() => new Set(battle.buffs.map((b) => b.defId)))

function isLocked(entry: { skill: any }) {
  const skill = entry.skill
  const reqBuffs = (skill as any).requiresBuffs as string[] | undefined
  const reqStacks = (skill as any).requiresBuffStacks as { buffId: string; stacks: number } | undefined
  const lockedByBuffs = reqBuffs ? !reqBuffs.every((id) => activeBuffIds.value.has(id)) : false
  const lockedByStacks = reqStacks
    ? (battle.buffs.find((b) => b.defId === reqStacks.buffId)?.stacks ?? 0) < reqStacks.stacks
    : false
  const lockedByMp = skill.mpCost > 0 && battle.playerMp.current < skill.mpCost
  return lockedByBuffs || lockedByStacks || lockedByMp
}

function cdTotal(entry: { skill: any }) {
  return entry.skill.gcd ? battle.gcdState.total : entry.skill.cooldown ?? 0
}
function activeCd(entry: { skill: any }) {
  return entry.skill.gcd ? battle.gcdState.remaining : battle.cooldowns.get(entry.skill.id) ?? 0
}
function cdPct(entry: { skill: any }) {
  const t = cdTotal(entry)
  const a = activeCd(entry)
  return t > 0 && a > 0 ? (a / t) * 100 : 0
}
function cdText(entry: { skill: any }) {
  const a = activeCd(entry)
  return a > 0 ? (a / 1000).toFixed(1) : null
}

function onEnter(e: MouseEvent, entry: { skill: any }) {
  const html = buildSkillTooltip(
    entry.skill,
    battle.buffDefs.size > 0 ? battle.buffDefs : undefined,
    battle.tooltipContext
  )
  tooltip.show(html, e.clientX, e.clientY)
}
function onLeave() {
  tooltip.hide()
}
</script>

<template lang="pug">
.skill-bar
  .skill-slot(
    v-for="entry in battle.skillBarEntries"
    :key="entry.key"
    :class="{ locked: isLocked(entry) }"
    @mouseenter="(e) => onEnter(e, entry)"
    @mousemove="(e) => onEnter(e, entry)"
    @mouseleave="onLeave"
  )
    span.slot-key {{ entry.key }}
    img.slot-icon(v-if="entry.skill.icon" :src="entry.skill.icon")
    span.slot-fallback(v-else) {{ entry.skill.name.slice(0, 3) }}
    .slot-cd-overlay(v-if="cdPct(entry) > 0" :style="{ height: cdPct(entry) + '%' }")
    span.slot-cd-text(v-if="cdText(entry)") {{ cdText(entry) }}
</template>

<style lang="scss" scoped>
.skill-bar {
  position: absolute;
  bottom: 20px;
  left: 50%;
  transform: translateX(-50%);
  display: flex;
  gap: 6px;
  pointer-events: auto;
}

.skill-slot {
  width: 48px;
  height: 48px;
  background: rgba(0, 0, 0, 0.8);
  border: 2px solid rgba(255, 255, 255, 0.4);
  border-radius: 4px;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  font-size: 12px;
  cursor: default;

  &.locked {
    border-color: rgba(255, 50, 50, 0.4);
    opacity: 0.5;
  }
}

.slot-key {
  position: absolute;
  top: 2px;
  left: 4px;
  font-size: 10px;
  color: rgba(255, 255, 255, 0.5);
}

.slot-icon {
  width: 40px;
  height: 40px;
  object-fit: contain;
  pointer-events: none;
}

.slot-fallback {
  font-size: 9px;
  text-align: center;
}

.slot-cd-overlay {
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  background: rgba(0, 0, 0, 0.7);
}

.slot-cd-text {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 14px;
  font-weight: bold;
  z-index: 1;
  text-shadow: 1px 1px 2px #000;
}
</style>

// src/ui/components/SkillBar.tsx
import { skillBarEntries, cooldowns, gcdState, buffDefs, buffs, tooltipContext } from '../state'
import { buildSkillTooltip } from '../tooltip-builders'
import { showTooltip, hideTooltip } from './Tooltip'

export function SkillBar() {
  const entries = skillBarEntries.value
  const cds = cooldowns.value
  const gcd = gcdState.value
  const defs = buffDefs.value
  const activeBuffIds = new Set(buffs.value.map(b => b.defId))
  const ctx = tooltipContext.value

  return (
    <div
      style={{
        position: 'absolute', bottom: 20, left: '50%', transform: 'translateX(-50%)',
        display: 'flex', gap: 6, pointerEvents: 'auto',
      }}
    >
      {entries.map((entry) => {
        const skill = entry.skill
        const isGcd = skill.gcd ?? false
        const cdRemaining = cds.get(skill.id) ?? 0
        const cdTotal = isGcd ? gcd.total : (skill.cooldown ?? 0)
        const active = isGcd ? gcd.remaining : cdRemaining
        const cdPct = cdTotal > 0 && active > 0 ? (active / cdTotal) * 100 : 0
        const cdText = active > 0 ? (active / 1000).toFixed(1) : null
        const reqBuffs = (skill as any).requiresBuffs as string[] | undefined
        const reqStacks = (skill as any).requiresBuffStacks as { buffId: string; stacks: number } | undefined
        const lockedByBuffs = reqBuffs ? !reqBuffs.every(id => activeBuffIds.has(id)) : false
        const lockedByStacks = reqStacks
          ? (buffs.value.find(b => b.defId === reqStacks.buffId)?.stacks ?? 0) < reqStacks.stacks
          : false
        const locked = lockedByBuffs || lockedByStacks

        return (
          <div
            key={entry.key}
            style={{
              width: 48, height: 48,
              background: 'rgba(0,0,0,0.8)',
              border: locked ? '2px solid rgba(255,50,50,0.4)' : '2px solid rgba(255,255,255,0.4)',
              opacity: locked ? 0.5 : 1,
              borderRadius: 4,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              position: 'relative', fontSize: 12, cursor: 'default',
            }}
            onMouseEnter={(e) => {
              const html = buildSkillTooltip(skill as any, defs.size > 0 ? defs as any : undefined, ctx)
              showTooltip(html, e.clientX, e.clientY)
            }}
            onMouseMove={(e) => {
              const html = buildSkillTooltip(skill as any, defs.size > 0 ? defs as any : undefined, ctx)
              showTooltip(html, e.clientX, e.clientY)
            }}
            onMouseLeave={hideTooltip}
          >
            <span style={{ position: 'absolute', top: 2, left: 4, fontSize: 10, color: 'rgba(255,255,255,0.5)' }}>
              {entry.key}
            </span>
            {skill.icon
              ? <img src={skill.icon} style={{ width: 40, height: 40, objectFit: 'contain', pointerEvents: 'none' }} />
              : <span style={{ fontSize: 9, textAlign: 'center' }}>{skill.name.slice(0, 3)}</span>
            }
            {cdPct > 0 && (
              <div
                style={{
                  position: 'absolute', bottom: 0, left: 0, width: '100%',
                  height: `${cdPct}%`, background: 'rgba(0,0,0,0.7)',
                }}
              />
            )}
            {cdText && (
              <span
                style={{
                  position: 'absolute', top: '50%', left: '50%',
                  transform: 'translate(-50%, -50%)',
                  fontSize: 14, fontWeight: 'bold', zIndex: 1,
                  textShadow: '1px 1px 2px #000',
                }}
              >
                {cdText}
              </span>
            )}
          </div>
        )
      })}
    </div>
  )
}
